//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InserirAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAlunoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirAulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirAvaliacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarAvaliacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirAvaliacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAvaliacaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDisciplinaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEnsinoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirFaltaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarFaltaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirFaltaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarFaltaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirTurmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarTurmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirTurmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTurmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTipoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirDisciplinaTurmaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarDisciplinaTurmaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InserirAlunoCompletedEventHandler InserirAlunoCompleted;
        
        /// <remarks/>
        public event AlterarAlunoCompletedEventHandler AlterarAlunoCompleted;
        
        /// <remarks/>
        public event ExcluirAlunoCompletedEventHandler ExcluirAlunoCompleted;
        
        /// <remarks/>
        public event ListarAlunoCompletedEventHandler ListarAlunoCompleted;
        
        /// <remarks/>
        public event InserirAulaCompletedEventHandler InserirAulaCompleted;
        
        /// <remarks/>
        public event AlterarAulaCompletedEventHandler AlterarAulaCompleted;
        
        /// <remarks/>
        public event ExcluirAulaCompletedEventHandler ExcluirAulaCompleted;
        
        /// <remarks/>
        public event ListarAulaCompletedEventHandler ListarAulaCompleted;
        
        /// <remarks/>
        public event InserirAvaliacaoCompletedEventHandler InserirAvaliacaoCompleted;
        
        /// <remarks/>
        public event AlterarAvaliacaoCompletedEventHandler AlterarAvaliacaoCompleted;
        
        /// <remarks/>
        public event ExcluirAvaliacaoCompletedEventHandler ExcluirAvaliacaoCompleted;
        
        /// <remarks/>
        public event ListarAvaliacaoCompletedEventHandler ListarAvaliacaoCompleted;
        
        /// <remarks/>
        public event ListarDisciplinaCompletedEventHandler ListarDisciplinaCompleted;
        
        /// <remarks/>
        public event ListarEnsinoCompletedEventHandler ListarEnsinoCompleted;
        
        /// <remarks/>
        public event InserirFaltaCompletedEventHandler InserirFaltaCompleted;
        
        /// <remarks/>
        public event AlterarFaltaCompletedEventHandler AlterarFaltaCompleted;
        
        /// <remarks/>
        public event ExcluirFaltaCompletedEventHandler ExcluirFaltaCompleted;
        
        /// <remarks/>
        public event ListarFaltaCompletedEventHandler ListarFaltaCompleted;
        
        /// <remarks/>
        public event InserirTurmaCompletedEventHandler InserirTurmaCompleted;
        
        /// <remarks/>
        public event AlterarTurmaCompletedEventHandler AlterarTurmaCompleted;
        
        /// <remarks/>
        public event ExcluirTurmaCompletedEventHandler ExcluirTurmaCompleted;
        
        /// <remarks/>
        public event ListarTurmaCompletedEventHandler ListarTurmaCompleted;
        
        /// <remarks/>
        public event ListarTipoUsuarioCompletedEventHandler ListarTipoUsuarioCompleted;
        
        /// <remarks/>
        public event InserirUsuarioCompletedEventHandler InserirUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarUsuarioCompletedEventHandler AlterarUsuarioCompleted;
        
        /// <remarks/>
        public event ExcluirUsuarioCompletedEventHandler ExcluirUsuarioCompleted;
        
        /// <remarks/>
        public event ListarUsuarioCompletedEventHandler ListarUsuarioCompleted;
        
        /// <remarks/>
        public event InserirDisciplinaTurmaCompletedEventHandler InserirDisciplinaTurmaCompleted;
        
        /// <remarks/>
        public event ListarDisciplinaTurmaCompletedEventHandler ListarDisciplinaTurmaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirAluno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirAluno([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aluno aluno) {
            this.Invoke("InserirAluno", new object[] {
                        aluno});
        }
        
        /// <remarks/>
        public void InserirAlunoAsync(Aluno aluno) {
            this.InserirAlunoAsync(aluno, null);
        }
        
        /// <remarks/>
        public void InserirAlunoAsync(Aluno aluno, object userState) {
            if ((this.InserirAlunoOperationCompleted == null)) {
                this.InserirAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirAlunoOperationCompleted);
            }
            this.InvokeAsync("InserirAluno", new object[] {
                        aluno}, this.InserirAlunoOperationCompleted, userState);
        }
        
        private void OnInserirAlunoOperationCompleted(object arg) {
            if ((this.InserirAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirAlunoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarAluno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarAluno([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aluno aluno) {
            this.Invoke("AlterarAluno", new object[] {
                        aluno});
        }
        
        /// <remarks/>
        public void AlterarAlunoAsync(Aluno aluno) {
            this.AlterarAlunoAsync(aluno, null);
        }
        
        /// <remarks/>
        public void AlterarAlunoAsync(Aluno aluno, object userState) {
            if ((this.AlterarAlunoOperationCompleted == null)) {
                this.AlterarAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAlunoOperationCompleted);
            }
            this.InvokeAsync("AlterarAluno", new object[] {
                        aluno}, this.AlterarAlunoOperationCompleted, userState);
        }
        
        private void OnAlterarAlunoOperationCompleted(object arg) {
            if ((this.AlterarAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAlunoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAluno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAluno([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aluno aluno) {
            this.Invoke("ExcluirAluno", new object[] {
                        aluno});
        }
        
        /// <remarks/>
        public void ExcluirAlunoAsync(Aluno aluno) {
            this.ExcluirAlunoAsync(aluno, null);
        }
        
        /// <remarks/>
        public void ExcluirAlunoAsync(Aluno aluno, object userState) {
            if ((this.ExcluirAlunoOperationCompleted == null)) {
                this.ExcluirAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAlunoOperationCompleted);
            }
            this.InvokeAsync("ExcluirAluno", new object[] {
                        aluno}, this.ExcluirAlunoOperationCompleted, userState);
        }
        
        private void OnExcluirAlunoOperationCompleted(object arg) {
            if ((this.ExcluirAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAlunoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAluno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Aluno[] ListarAluno([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aluno aluno) {
            object[] results = this.Invoke("ListarAluno", new object[] {
                        aluno});
            return ((Aluno[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAlunoAsync(Aluno aluno) {
            this.ListarAlunoAsync(aluno, null);
        }
        
        /// <remarks/>
        public void ListarAlunoAsync(Aluno aluno, object userState) {
            if ((this.ListarAlunoOperationCompleted == null)) {
                this.ListarAlunoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAlunoOperationCompleted);
            }
            this.InvokeAsync("ListarAluno", new object[] {
                        aluno}, this.ListarAlunoOperationCompleted, userState);
        }
        
        private void OnListarAlunoOperationCompleted(object arg) {
            if ((this.ListarAlunoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAlunoCompleted(this, new ListarAlunoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirAula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirAula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aula aula) {
            this.Invoke("InserirAula", new object[] {
                        aula});
        }
        
        /// <remarks/>
        public void InserirAulaAsync(Aula aula) {
            this.InserirAulaAsync(aula, null);
        }
        
        /// <remarks/>
        public void InserirAulaAsync(Aula aula, object userState) {
            if ((this.InserirAulaOperationCompleted == null)) {
                this.InserirAulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirAulaOperationCompleted);
            }
            this.InvokeAsync("InserirAula", new object[] {
                        aula}, this.InserirAulaOperationCompleted, userState);
        }
        
        private void OnInserirAulaOperationCompleted(object arg) {
            if ((this.InserirAulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirAulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarAula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarAula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aula aula) {
            this.Invoke("AlterarAula", new object[] {
                        aula});
        }
        
        /// <remarks/>
        public void AlterarAulaAsync(Aula aula) {
            this.AlterarAulaAsync(aula, null);
        }
        
        /// <remarks/>
        public void AlterarAulaAsync(Aula aula, object userState) {
            if ((this.AlterarAulaOperationCompleted == null)) {
                this.AlterarAulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAulaOperationCompleted);
            }
            this.InvokeAsync("AlterarAula", new object[] {
                        aula}, this.AlterarAulaOperationCompleted, userState);
        }
        
        private void OnAlterarAulaOperationCompleted(object arg) {
            if ((this.AlterarAulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aula aula) {
            this.Invoke("ExcluirAula", new object[] {
                        aula});
        }
        
        /// <remarks/>
        public void ExcluirAulaAsync(Aula aula) {
            this.ExcluirAulaAsync(aula, null);
        }
        
        /// <remarks/>
        public void ExcluirAulaAsync(Aula aula, object userState) {
            if ((this.ExcluirAulaOperationCompleted == null)) {
                this.ExcluirAulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAulaOperationCompleted);
            }
            this.InvokeAsync("ExcluirAula", new object[] {
                        aula}, this.ExcluirAulaOperationCompleted, userState);
        }
        
        private void OnExcluirAulaOperationCompleted(object arg) {
            if ((this.ExcluirAulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAulaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Aula[] ListarAula([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Aula aula) {
            object[] results = this.Invoke("ListarAula", new object[] {
                        aula});
            return ((Aula[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAulaAsync(Aula aula) {
            this.ListarAulaAsync(aula, null);
        }
        
        /// <remarks/>
        public void ListarAulaAsync(Aula aula, object userState) {
            if ((this.ListarAulaOperationCompleted == null)) {
                this.ListarAulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAulaOperationCompleted);
            }
            this.InvokeAsync("ListarAula", new object[] {
                        aula}, this.ListarAulaOperationCompleted, userState);
        }
        
        private void OnListarAulaOperationCompleted(object arg) {
            if ((this.ListarAulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAulaCompleted(this, new ListarAulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirAvaliacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirAvaliacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Avaliacao avaliacao) {
            this.Invoke("InserirAvaliacao", new object[] {
                        avaliacao});
        }
        
        /// <remarks/>
        public void InserirAvaliacaoAsync(Avaliacao avaliacao) {
            this.InserirAvaliacaoAsync(avaliacao, null);
        }
        
        /// <remarks/>
        public void InserirAvaliacaoAsync(Avaliacao avaliacao, object userState) {
            if ((this.InserirAvaliacaoOperationCompleted == null)) {
                this.InserirAvaliacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirAvaliacaoOperationCompleted);
            }
            this.InvokeAsync("InserirAvaliacao", new object[] {
                        avaliacao}, this.InserirAvaliacaoOperationCompleted, userState);
        }
        
        private void OnInserirAvaliacaoOperationCompleted(object arg) {
            if ((this.InserirAvaliacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirAvaliacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarAvaliacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarAvaliacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Avaliacao avaliacao) {
            this.Invoke("AlterarAvaliacao", new object[] {
                        avaliacao});
        }
        
        /// <remarks/>
        public void AlterarAvaliacaoAsync(Avaliacao avaliacao) {
            this.AlterarAvaliacaoAsync(avaliacao, null);
        }
        
        /// <remarks/>
        public void AlterarAvaliacaoAsync(Avaliacao avaliacao, object userState) {
            if ((this.AlterarAvaliacaoOperationCompleted == null)) {
                this.AlterarAvaliacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarAvaliacaoOperationCompleted);
            }
            this.InvokeAsync("AlterarAvaliacao", new object[] {
                        avaliacao}, this.AlterarAvaliacaoOperationCompleted, userState);
        }
        
        private void OnAlterarAvaliacaoOperationCompleted(object arg) {
            if ((this.AlterarAvaliacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarAvaliacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirAvaliacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirAvaliacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Avaliacao avaliacao) {
            this.Invoke("ExcluirAvaliacao", new object[] {
                        avaliacao});
        }
        
        /// <remarks/>
        public void ExcluirAvaliacaoAsync(Avaliacao avaliacao) {
            this.ExcluirAvaliacaoAsync(avaliacao, null);
        }
        
        /// <remarks/>
        public void ExcluirAvaliacaoAsync(Avaliacao avaliacao, object userState) {
            if ((this.ExcluirAvaliacaoOperationCompleted == null)) {
                this.ExcluirAvaliacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirAvaliacaoOperationCompleted);
            }
            this.InvokeAsync("ExcluirAvaliacao", new object[] {
                        avaliacao}, this.ExcluirAvaliacaoOperationCompleted, userState);
        }
        
        private void OnExcluirAvaliacaoOperationCompleted(object arg) {
            if ((this.ExcluirAvaliacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirAvaliacaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarAvaliacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Avaliacao[] ListarAvaliacao([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Avaliacao avaliacao) {
            object[] results = this.Invoke("ListarAvaliacao", new object[] {
                        avaliacao});
            return ((Avaliacao[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAvaliacaoAsync(Avaliacao avaliacao) {
            this.ListarAvaliacaoAsync(avaliacao, null);
        }
        
        /// <remarks/>
        public void ListarAvaliacaoAsync(Avaliacao avaliacao, object userState) {
            if ((this.ListarAvaliacaoOperationCompleted == null)) {
                this.ListarAvaliacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAvaliacaoOperationCompleted);
            }
            this.InvokeAsync("ListarAvaliacao", new object[] {
                        avaliacao}, this.ListarAvaliacaoOperationCompleted, userState);
        }
        
        private void OnListarAvaliacaoOperationCompleted(object arg) {
            if ((this.ListarAvaliacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAvaliacaoCompleted(this, new ListarAvaliacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarDisciplina", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Disciplina[] ListarDisciplina([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Disciplina disciplina) {
            object[] results = this.Invoke("ListarDisciplina", new object[] {
                        disciplina});
            return ((Disciplina[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDisciplinaAsync(Disciplina disciplina) {
            this.ListarDisciplinaAsync(disciplina, null);
        }
        
        /// <remarks/>
        public void ListarDisciplinaAsync(Disciplina disciplina, object userState) {
            if ((this.ListarDisciplinaOperationCompleted == null)) {
                this.ListarDisciplinaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDisciplinaOperationCompleted);
            }
            this.InvokeAsync("ListarDisciplina", new object[] {
                        disciplina}, this.ListarDisciplinaOperationCompleted, userState);
        }
        
        private void OnListarDisciplinaOperationCompleted(object arg) {
            if ((this.ListarDisciplinaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDisciplinaCompleted(this, new ListarDisciplinaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarEnsino", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Ensino[] ListarEnsino([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Ensino ensino) {
            object[] results = this.Invoke("ListarEnsino", new object[] {
                        ensino});
            return ((Ensino[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEnsinoAsync(Ensino ensino) {
            this.ListarEnsinoAsync(ensino, null);
        }
        
        /// <remarks/>
        public void ListarEnsinoAsync(Ensino ensino, object userState) {
            if ((this.ListarEnsinoOperationCompleted == null)) {
                this.ListarEnsinoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEnsinoOperationCompleted);
            }
            this.InvokeAsync("ListarEnsino", new object[] {
                        ensino}, this.ListarEnsinoOperationCompleted, userState);
        }
        
        private void OnListarEnsinoOperationCompleted(object arg) {
            if ((this.ListarEnsinoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEnsinoCompleted(this, new ListarEnsinoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirFalta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirFalta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Falta falta) {
            this.Invoke("InserirFalta", new object[] {
                        falta});
        }
        
        /// <remarks/>
        public void InserirFaltaAsync(Falta falta) {
            this.InserirFaltaAsync(falta, null);
        }
        
        /// <remarks/>
        public void InserirFaltaAsync(Falta falta, object userState) {
            if ((this.InserirFaltaOperationCompleted == null)) {
                this.InserirFaltaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirFaltaOperationCompleted);
            }
            this.InvokeAsync("InserirFalta", new object[] {
                        falta}, this.InserirFaltaOperationCompleted, userState);
        }
        
        private void OnInserirFaltaOperationCompleted(object arg) {
            if ((this.InserirFaltaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirFaltaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarFalta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarFalta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Falta falta) {
            this.Invoke("AlterarFalta", new object[] {
                        falta});
        }
        
        /// <remarks/>
        public void AlterarFaltaAsync(Falta falta) {
            this.AlterarFaltaAsync(falta, null);
        }
        
        /// <remarks/>
        public void AlterarFaltaAsync(Falta falta, object userState) {
            if ((this.AlterarFaltaOperationCompleted == null)) {
                this.AlterarFaltaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarFaltaOperationCompleted);
            }
            this.InvokeAsync("AlterarFalta", new object[] {
                        falta}, this.AlterarFaltaOperationCompleted, userState);
        }
        
        private void OnAlterarFaltaOperationCompleted(object arg) {
            if ((this.AlterarFaltaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarFaltaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirFalta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirFalta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Falta falta) {
            this.Invoke("ExcluirFalta", new object[] {
                        falta});
        }
        
        /// <remarks/>
        public void ExcluirFaltaAsync(Falta falta) {
            this.ExcluirFaltaAsync(falta, null);
        }
        
        /// <remarks/>
        public void ExcluirFaltaAsync(Falta falta, object userState) {
            if ((this.ExcluirFaltaOperationCompleted == null)) {
                this.ExcluirFaltaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirFaltaOperationCompleted);
            }
            this.InvokeAsync("ExcluirFalta", new object[] {
                        falta}, this.ExcluirFaltaOperationCompleted, userState);
        }
        
        private void OnExcluirFaltaOperationCompleted(object arg) {
            if ((this.ExcluirFaltaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirFaltaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarFalta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Falta[] ListarFalta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Falta falta) {
            object[] results = this.Invoke("ListarFalta", new object[] {
                        falta});
            return ((Falta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarFaltaAsync(Falta falta) {
            this.ListarFaltaAsync(falta, null);
        }
        
        /// <remarks/>
        public void ListarFaltaAsync(Falta falta, object userState) {
            if ((this.ListarFaltaOperationCompleted == null)) {
                this.ListarFaltaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarFaltaOperationCompleted);
            }
            this.InvokeAsync("ListarFalta", new object[] {
                        falta}, this.ListarFaltaOperationCompleted, userState);
        }
        
        private void OnListarFaltaOperationCompleted(object arg) {
            if ((this.ListarFaltaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarFaltaCompleted(this, new ListarFaltaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirTurma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirTurma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Turma turma) {
            this.Invoke("InserirTurma", new object[] {
                        turma});
        }
        
        /// <remarks/>
        public void InserirTurmaAsync(Turma turma) {
            this.InserirTurmaAsync(turma, null);
        }
        
        /// <remarks/>
        public void InserirTurmaAsync(Turma turma, object userState) {
            if ((this.InserirTurmaOperationCompleted == null)) {
                this.InserirTurmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirTurmaOperationCompleted);
            }
            this.InvokeAsync("InserirTurma", new object[] {
                        turma}, this.InserirTurmaOperationCompleted, userState);
        }
        
        private void OnInserirTurmaOperationCompleted(object arg) {
            if ((this.InserirTurmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirTurmaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarTurma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarTurma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Turma turma) {
            this.Invoke("AlterarTurma", new object[] {
                        turma});
        }
        
        /// <remarks/>
        public void AlterarTurmaAsync(Turma turma) {
            this.AlterarTurmaAsync(turma, null);
        }
        
        /// <remarks/>
        public void AlterarTurmaAsync(Turma turma, object userState) {
            if ((this.AlterarTurmaOperationCompleted == null)) {
                this.AlterarTurmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarTurmaOperationCompleted);
            }
            this.InvokeAsync("AlterarTurma", new object[] {
                        turma}, this.AlterarTurmaOperationCompleted, userState);
        }
        
        private void OnAlterarTurmaOperationCompleted(object arg) {
            if ((this.AlterarTurmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarTurmaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirTurma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirTurma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Turma turma) {
            this.Invoke("ExcluirTurma", new object[] {
                        turma});
        }
        
        /// <remarks/>
        public void ExcluirTurmaAsync(Turma turma) {
            this.ExcluirTurmaAsync(turma, null);
        }
        
        /// <remarks/>
        public void ExcluirTurmaAsync(Turma turma, object userState) {
            if ((this.ExcluirTurmaOperationCompleted == null)) {
                this.ExcluirTurmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirTurmaOperationCompleted);
            }
            this.InvokeAsync("ExcluirTurma", new object[] {
                        turma}, this.ExcluirTurmaOperationCompleted, userState);
        }
        
        private void OnExcluirTurmaOperationCompleted(object arg) {
            if ((this.ExcluirTurmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirTurmaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarTurma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Turma[] ListarTurma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Turma turma) {
            object[] results = this.Invoke("ListarTurma", new object[] {
                        turma});
            return ((Turma[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTurmaAsync(Turma turma) {
            this.ListarTurmaAsync(turma, null);
        }
        
        /// <remarks/>
        public void ListarTurmaAsync(Turma turma, object userState) {
            if ((this.ListarTurmaOperationCompleted == null)) {
                this.ListarTurmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTurmaOperationCompleted);
            }
            this.InvokeAsync("ListarTurma", new object[] {
                        turma}, this.ListarTurmaOperationCompleted, userState);
        }
        
        private void OnListarTurmaOperationCompleted(object arg) {
            if ((this.ListarTurmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTurmaCompleted(this, new ListarTurmaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarTipoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public TipoUsuario[] ListarTipoUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoUsuario tipoUsuario) {
            object[] results = this.Invoke("ListarTipoUsuario", new object[] {
                        tipoUsuario});
            return ((TipoUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTipoUsuarioAsync(TipoUsuario tipoUsuario) {
            this.ListarTipoUsuarioAsync(tipoUsuario, null);
        }
        
        /// <remarks/>
        public void ListarTipoUsuarioAsync(TipoUsuario tipoUsuario, object userState) {
            if ((this.ListarTipoUsuarioOperationCompleted == null)) {
                this.ListarTipoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTipoUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarTipoUsuario", new object[] {
                        tipoUsuario}, this.ListarTipoUsuarioOperationCompleted, userState);
        }
        
        private void OnListarTipoUsuarioOperationCompleted(object arg) {
            if ((this.ListarTipoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTipoUsuarioCompleted(this, new ListarTipoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("InserirUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void InserirUsuarioAsync(Usuario usuario) {
            this.InserirUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void InserirUsuarioAsync(Usuario usuario, object userState) {
            if ((this.InserirUsuarioOperationCompleted == null)) {
                this.InserirUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirUsuarioOperationCompleted);
            }
            this.InvokeAsync("InserirUsuario", new object[] {
                        usuario}, this.InserirUsuarioOperationCompleted, userState);
        }
        
        private void OnInserirUsuarioOperationCompleted(object arg) {
            if ((this.InserirUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("AlterarUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario) {
            this.AlterarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.AlterarUsuarioOperationCompleted == null)) {
                this.AlterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AlterarUsuario", new object[] {
                        usuario}, this.AlterarUsuarioOperationCompleted, userState);
        }
        
        private void OnAlterarUsuarioOperationCompleted(object arg) {
            if ((this.AlterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ExcluirUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("ExcluirUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void ExcluirUsuarioAsync(Usuario usuario) {
            this.ExcluirUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ExcluirUsuarioAsync(Usuario usuario, object userState) {
            if ((this.ExcluirUsuarioOperationCompleted == null)) {
                this.ExcluirUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirUsuarioOperationCompleted);
            }
            this.InvokeAsync("ExcluirUsuario", new object[] {
                        usuario}, this.ExcluirUsuarioOperationCompleted, userState);
        }
        
        private void OnExcluirUsuarioOperationCompleted(object arg) {
            if ((this.ExcluirUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Usuario[] ListarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            object[] results = this.Invoke("ListarUsuario", new object[] {
                        usuario});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(Usuario usuario) {
            this.ListarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.ListarUsuarioOperationCompleted == null)) {
                this.ListarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarUsuario", new object[] {
                        usuario}, this.ListarUsuarioOperationCompleted, userState);
        }
        
        private void OnListarUsuarioOperationCompleted(object arg) {
            if ((this.ListarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuarioCompleted(this, new ListarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirDisciplinaTurma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirDisciplinaTurma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Disciplina_Turma dt) {
            this.Invoke("InserirDisciplinaTurma", new object[] {
                        dt});
        }
        
        /// <remarks/>
        public void InserirDisciplinaTurmaAsync(Disciplina_Turma dt) {
            this.InserirDisciplinaTurmaAsync(dt, null);
        }
        
        /// <remarks/>
        public void InserirDisciplinaTurmaAsync(Disciplina_Turma dt, object userState) {
            if ((this.InserirDisciplinaTurmaOperationCompleted == null)) {
                this.InserirDisciplinaTurmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirDisciplinaTurmaOperationCompleted);
            }
            this.InvokeAsync("InserirDisciplinaTurma", new object[] {
                        dt}, this.InserirDisciplinaTurmaOperationCompleted, userState);
        }
        
        private void OnInserirDisciplinaTurmaOperationCompleted(object arg) {
            if ((this.InserirDisciplinaTurmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirDisciplinaTurmaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarDisciplinaTurma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
        public Disciplina_Turma[] ListarDisciplinaTurma([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Disciplina_Turma dt) {
            object[] results = this.Invoke("ListarDisciplinaTurma", new object[] {
                        dt});
            return ((Disciplina_Turma[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarDisciplinaTurmaAsync(Disciplina_Turma dt) {
            this.ListarDisciplinaTurmaAsync(dt, null);
        }
        
        /// <remarks/>
        public void ListarDisciplinaTurmaAsync(Disciplina_Turma dt, object userState) {
            if ((this.ListarDisciplinaTurmaOperationCompleted == null)) {
                this.ListarDisciplinaTurmaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarDisciplinaTurmaOperationCompleted);
            }
            this.InvokeAsync("ListarDisciplinaTurma", new object[] {
                        dt}, this.ListarDisciplinaTurmaOperationCompleted, userState);
        }
        
        private void OnListarDisciplinaTurmaOperationCompleted(object arg) {
            if ((this.ListarDisciplinaTurmaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarDisciplinaTurmaCompleted(this, new ListarDisciplinaTurmaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Aluno {
        
        private System.DateTime dataNascField;
        
        private string matriculaField;
        
        private string nomeField;
        
        private string sexoField;
        
        private string telefoneField;
        
        private Turma turmaField;
        
        /// <remarks/>
        public System.DateTime DataNasc {
            get {
                return this.dataNascField;
            }
            set {
                this.dataNascField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Turma Turma {
            get {
                return this.turmaField;
            }
            set {
                this.turmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Turma {
        
        private int anoField;
        
        private int codigoTurmaField;
        
        private System.DateTime dataInicioField;
        
        private string descricaoTurmaField;
        
        private Ensino ensinoField;
        
        private string turnoField;
        
        /// <remarks/>
        public int Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoTurma {
            get {
                return this.codigoTurmaField;
            }
            set {
                this.codigoTurmaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescricaoTurma {
            get {
                return this.descricaoTurmaField;
            }
            set {
                this.descricaoTurmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Ensino Ensino {
            get {
                return this.ensinoField;
            }
            set {
                this.ensinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Turno {
            get {
                return this.turnoField;
            }
            set {
                this.turnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Ensino {
        
        private int codigoEnsinoField;
        
        private string descricaoEnsinoField;
        
        /// <remarks/>
        public int CodigoEnsino {
            get {
                return this.codigoEnsinoField;
            }
            set {
                this.codigoEnsinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescricaoEnsino {
            get {
                return this.descricaoEnsinoField;
            }
            set {
                this.descricaoEnsinoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Falta {
        
        private bool abonoField;
        
        private bool abonoFieldSpecified;
        
        private Aluno alunoField;
        
        private Aula aulaField;
        
        private int codigoFaltaField;
        
        private bool codigoFaltaFieldSpecified;
        
        private string dataField;
        
        private string motivoField;
        
        /// <remarks/>
        public bool Abono {
            get {
                return this.abonoField;
            }
            set {
                this.abonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AbonoSpecified {
            get {
                return this.abonoFieldSpecified;
            }
            set {
                this.abonoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Aluno Aluno {
            get {
                return this.alunoField;
            }
            set {
                this.alunoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Aula Aula {
            get {
                return this.aulaField;
            }
            set {
                this.aulaField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoFalta {
            get {
                return this.codigoFaltaField;
            }
            set {
                this.codigoFaltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoFaltaSpecified {
            get {
                return this.codigoFaltaFieldSpecified;
            }
            set {
                this.codigoFaltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Aula {
        
        private string assuntoField;
        
        private int codigoAulaField;
        
        private string dataField;
        
        private Disciplina_Turma disciplinaTurmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Assunto {
            get {
                return this.assuntoField;
            }
            set {
                this.assuntoField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoAula {
            get {
                return this.codigoAulaField;
            }
            set {
                this.codigoAulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Disciplina_Turma DisciplinaTurma {
            get {
                return this.disciplinaTurmaField;
            }
            set {
                this.disciplinaTurmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Disciplina_Turma {
        
        private int codigoDisciplinaTurmaField;
        
        private Disciplina disciplinaField;
        
        private Turma turmaField;
        
        private Usuario usuarioField;
        
        /// <remarks/>
        public int CodigoDisciplinaTurma {
            get {
                return this.codigoDisciplinaTurmaField;
            }
            set {
                this.codigoDisciplinaTurmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Disciplina Disciplina {
            get {
                return this.disciplinaField;
            }
            set {
                this.disciplinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Turma Turma {
            get {
                return this.turmaField;
            }
            set {
                this.turmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Disciplina {
        
        private int codigoDisciplinaField;
        
        private string nomeDisciplinaField;
        
        /// <remarks/>
        public int CodigoDisciplina {
            get {
                return this.codigoDisciplinaField;
            }
            set {
                this.codigoDisciplinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomeDisciplina {
            get {
                return this.nomeDisciplinaField;
            }
            set {
                this.nomeDisciplinaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Usuario {
        
        private int codUsuarioField;
        
        private string loginUsuarioField;
        
        private string nomeField;
        
        private string senhaField;
        
        private string telefoneField;
        
        private TipoUsuario tipoUsuarioField;
        
        /// <remarks/>
        public int CodUsuario {
            get {
                return this.codUsuarioField;
            }
            set {
                this.codUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoginUsuario {
            get {
                return this.loginUsuarioField;
            }
            set {
                this.loginUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoUsuario TipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class TipoUsuario {
        
        private int codTipoUsuarioField;
        
        private string descricaoTipoUsuarioField;
        
        /// <remarks/>
        public int CodTipoUsuario {
            get {
                return this.codTipoUsuarioField;
            }
            set {
                this.codTipoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescricaoTipoUsuario {
            get {
                return this.descricaoTipoUsuarioField;
            }
            set {
                this.descricaoTipoUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Basicas")]
    public partial class Avaliacao {
        
        private Aluno alunoField;
        
        private int codigoAvaliacaoField;
        
        private string descricaoField;
        
        private Disciplina_Turma disciplina_turmaField;
        
        private double notaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Aluno Aluno {
            get {
                return this.alunoField;
            }
            set {
                this.alunoField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoAvaliacao {
            get {
                return this.codigoAvaliacaoField;
            }
            set {
                this.codigoAvaliacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Disciplina_Turma Disciplina_turma {
            get {
                return this.disciplina_turmaField;
            }
            set {
                this.disciplina_turmaField = value;
            }
        }
        
        /// <remarks/>
        public double Nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirAlunoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarAlunoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirAlunoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarAlunoCompletedEventHandler(object sender, ListarAlunoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAlunoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAlunoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aluno[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aluno[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirAulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarAulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirAulaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarAulaCompletedEventHandler(object sender, ListarAulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aula[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aula[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirAvaliacaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarAvaliacaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirAvaliacaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarAvaliacaoCompletedEventHandler(object sender, ListarAvaliacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAvaliacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAvaliacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Avaliacao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Avaliacao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarDisciplinaCompletedEventHandler(object sender, ListarDisciplinaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDisciplinaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDisciplinaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Disciplina[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Disciplina[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarEnsinoCompletedEventHandler(object sender, ListarEnsinoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEnsinoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEnsinoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ensino[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ensino[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirFaltaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarFaltaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirFaltaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarFaltaCompletedEventHandler(object sender, ListarFaltaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarFaltaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarFaltaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Falta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Falta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirTurmaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarTurmaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirTurmaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarTurmaCompletedEventHandler(object sender, ListarTurmaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTurmaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTurmaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Turma[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Turma[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarTipoUsuarioCompletedEventHandler(object sender, ListarTipoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTipoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTipoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoUsuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AlterarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ExcluirUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarUsuarioCompletedEventHandler(object sender, ListarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InserirDisciplinaTurmaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListarDisciplinaTurmaCompletedEventHandler(object sender, ListarDisciplinaTurmaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarDisciplinaTurmaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarDisciplinaTurmaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Disciplina_Turma[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Disciplina_Turma[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591